name: sudomaze
description: cool blog
url: https://sudomaze.dev
encoding: "utf-8"
markdown: kramdown
highlighter: rouge
kramdown:
  input: GFM
  syntax_highlighter: rouge

plugins:
  - jekyll-paginate
  - jekyll-sitemap
  - jekyll-gist
  - jekyll-include-cache

include: ['_pages', '_notes']