title: "sudomaze.dev"
url: "https://sudomaze.dev"
repository: "sudomaze/sudomaze.github.io"
access_token: "U2FsdGVkX1/8V0sYchUExOfJ31D6hvd6Jpjpcj1NOJSmVR8+MjjIzFQW0bu14sUE4e3lpLGEST3pREgAV3zodg=="
disqus:
  shortname: "sudomaze"
  public_key: "xlagUgR5BxVFA7EduSkai8EPtVJopAosMcsY4UUHFevX39IsnZNFZepznkfgMKUo"

head_links:
  - /assets/libraries/bootstrap-4.3.1-dist/css/bootstrap.min.css
  - /assets/libraries/katex/katex.min.css
  - /assets/libraries/pseudocode.js-1.1/pseudocode.css
  - /assets/css/styles.css
  - /assets/libraries/github/github-calendar.css

head_scripts:
  - /assets/libraries/jquery-3.4.1/jquery-3.4.1.min.js
  - /assets/libraries/bootstrap-4.3.1-dist/js/bootstrap.min.js
  - /assets/libraries/katex/katex.min.js
  - /assets/libraries/pseudocode.js-1.1/pseudocode.js
  - /assets/libraries/github/github-calendar.min.js

footer_scripts:
  - /assets/js/index.js
