title: "sudomaze.dev"
name: "Mazen Alotaibi"
description: >
  Is a M.S. student under the supervision of <a href="http://web.engr.oregonstate.edu/~lif/">Prof. Fuxin Li</a>
  at Deep Machine Vision (DMV) in Oregon State University (OSU). He is interested in Computer Vision, Deep Learning,
  and Data Science.
profile_pic: /assets/img/profile.png
favicon: /assets/img/favicon.png
copyright_name: "Mazen Alotaibi"
url: "https://sudomaze.dev"
repository: "sudomaze/sudomaze.github.io"
disqus:
  shortname: "sudomaze"
  public_key: "xlagUgR5BxVFA7EduSkai8EPtVJopAosMcsY4UUHFevX39IsnZNFZepznkfgMKUo"

head_links:
  - /assets/libs/fontawesome/css/all.min.css
  - /assets/libs/katex/katex.min.css
  - /assets/libs/pseudocode.js/pseudocode.css
  - /assets/css/style.css
  - /assets/libs/github/github-calendar.css

head_scripts:
  - /assets/libs/jquery/jquery-3.4.1.min.js
  - /assets/libs/katex/katex.min.js
  - /assets/libs/pseudocode.js/pseudocode.js
  - /assets/libs/github/github-calendar.min.js

footer_scripts:
  - /assets/js/contextmenu.js
  - /assets/js/nightmode.js
