title: "sudomaze.dev"
profile_pic: /assets/img/profile.png
favicon: /assets/img/favicon.png
url: "https://sudomaze.dev"
repository: "sudomaze/sudomaze.github.io"
disqus:
  shortname: "sudomaze"
  public_key: "xlagUgR5BxVFA7EduSkai8EPtVJopAosMcsY4UUHFevX39IsnZNFZepznkfgMKUo"

head_scripts:
  - /assets/js/nightmode-loader.js
  - /assets/js/simple-jekyll-search.min.js

head_links:
  - /assets/libs/fontawesome/css/all.min.css
  - /assets/css/style.css

footer_scripts:
  - /assets/js/contextmenu.js
  - /assets/js/nightmode-event.js
