title: "3ziz.xyz"
profile_pic: /assets/img/3z.jpg
favicon: /assets/img/3z.jpg
url: "https://3ziz.xyz"
repository: "grepaziz/grepaziz.github.io"
disqus:
    shortname: "grepaziz"
    public_key: "xlagUgR5BxVFA7EduSkai8EPtVJopAosMcsY4UUHFevX39IsnZNFZepznkfgMKUo"

head_scripts:
    # - /assets/js/async_file.js

head_links:
    - /assets/libs/fontawesome/css/all.min.css
    - /assets/libs/highlight.js/styles/atom-one-dark.css

footer_scripts:
    - /assets/js/contextmenu.js
    - /assets/js/nightmode-event.js
    - /assets/js/collapsible.js
    - /assets/js/code-snippets.js
